// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBY58EnmraIaxjjDsSkXzpRr8k_aJ09GU',
    appId: '1:338011390486:web:ec4d9464f2243eeab96b37',
    messagingSenderId: '338011390486',
    projectId: 'chat-app-5384f',
    authDomain: 'chat-app-5384f.firebaseapp.com',
    storageBucket: 'chat-app-5384f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPk0_ugpav1wIuRo07xZ16OkbaQqTFz9I',
    appId: '1:338011390486:android:01aa5c1083b2ec27b96b37',
    messagingSenderId: '338011390486',
    projectId: 'chat-app-5384f',
    storageBucket: 'chat-app-5384f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCo_AvIWPmD9gjDbcXfSst_6kx2-9pL1o',
    appId: '1:338011390486:ios:bd0a5957f4324bf1b96b37',
    messagingSenderId: '338011390486',
    projectId: 'chat-app-5384f',
    storageBucket: 'chat-app-5384f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCo_AvIWPmD9gjDbcXfSst_6kx2-9pL1o',
    appId: '1:338011390486:ios:bd0a5957f4324bf1b96b37',
    messagingSenderId: '338011390486',
    projectId: 'chat-app-5384f',
    storageBucket: 'chat-app-5384f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBY58EnmraIaxjjDsSkXzpRr8k_aJ09GU',
    appId: '1:338011390486:web:d9bfb4b0ffa5d7b6b96b37',
    messagingSenderId: '338011390486',
    projectId: 'chat-app-5384f',
    authDomain: 'chat-app-5384f.firebaseapp.com',
    storageBucket: 'chat-app-5384f.appspot.com',
  );
}
